#pragma once

#include "IdaCompat.h"

enum ASYNC_LOG_TYPE : int
{
  ALT_ASYNC_LOGGER_SYSTEM_LOG = 0,
  ALT_PERFORMANCE_COUNTER_SYSTEM = 1,
  ALT_PERFORMANCE_MAIN_LOOP = 2,
  ALT_PERFORMANCE_MAIN_DQS = 3,
  ALT_PERFORMANCE_LOG_DQS = 4,
  ALT_PERFORMANCE_CASH_DQS = 5,
  ALT_PERFORMANCE_NETWORK_DQS = 6,
  ALT_FIREGUARD_DETECT_LOG = 7,
  ALT_HONOR_GUILD_LOG = 8,
  ALT_CLASSREFINE_SERVICE_LOG = 9,
  ALT_BUY_CASH_ITEM_LOG = 10,
  ALT_HACKSHIELD_SYSTEM_LOG = 11,
  ALT_APEX_SYSTEM_LOG = 12,
  ALT_GETGOLDBAR_LOG = 13,
  ALT_GETEVENTCOUPON_LOG = 14,
  ALT_MAX = 15,
  ALT_NONE = -1,
};
