#pragma once

#include "IdaCompat.h"

/* 1423 */
class __cppobj CBsp
{
  float (*mCVertex)[3];
  float (*mCNNormal)[3];
  unsigned int *mCVertexId;
  _BSP_C_FACE *mCFace;
  float (*mCNEdgeNormal)[4];
  unsigned int *mCFaceId;
  unsigned int *mVertexColor;
  __int16 (*mLgtUV)[2];
  int mNowCFaceId;
  unsigned __int16 *MatListInLeafId;
  unsigned int mMatGroupNum;
  _BSP_MAT_GROUP *mMatGroup;
  unsigned int mCVertexNum;
  unsigned int mCFaceNum;
  unsigned int mVertexNum;
  unsigned int mFaceNum;
  int mIsLoaded;
  unsigned int mObjectNum;
  _ANI_OBJECT *mObject;
  unsigned __int16 *mEventObjectID;
  unsigned int mEnvID[2];
  $1D4D54E2B5971D5BE0EAD557ED232A85 ___u21;
  CMergeFileManager mMapEntityMFM;
  int mIsLoadEBP;
  unsigned __int8 *mEntityCache;
  unsigned int mEntityCacheSize;
  unsigned int mNowRenderMatGroupNum;
  unsigned int mNowShadowMatGroupNum;
  CEntity *mEntity;
  CParticle *mParticle;
  _ENTITY_LIST *mEntityList;
  unsigned __int16 *mEntityID;
  _LEAF_ENTITIES_LIST_INFO *mLeafEntityList;
  _MAP_ENTITIES_LIST *mMapEntitiesList;
  unsigned int mEntityListNum;
  unsigned int mLeafEntityListNum;
  unsigned int mEntityIDNum;
  unsigned int mMapEntitiesListNum;
  unsigned __int8 *mSoundEntityCache;
  unsigned int mSoundEntityCacheSize;
  unsigned int mSoundEntityIDNum;
  unsigned int mLeafSoundEntityListNum;
  unsigned int mSoundEntityListNum;
  unsigned int mSoundEntitiesListNum;
  _SOUND_ENTITY_LIST *mSoundEntityList;
  _SOUND_ENTITIES_LIST *mSoundEntitiesList;
  unsigned __int16 *mSoundEntityID;
  _LEAF_SOUND_ENTITIES_LIST_INFO *mLeafSoundEntityList;
  unsigned int mTotalAllocSize;
  unsigned int mTotalWaveSize;
  unsigned int mVertexBufferSize;
  _BSP_NODE *mNode;
  _BSP_LEAF *mLeaf;
  unsigned int mLeafNum;
  unsigned int mNodeNum;
  unsigned int mCFVertexNum;
  unsigned int mCFLineNum;
  unsigned int mCFLineIdNum;
  float (*mCFVertex)[3];
  _TOOL_COL_LINE *mCFLine;
  unsigned __int16 *mCFLineId;
  _TOOL_COL_LEAF *mCFLeaf;
  float (*mCFVNormal)[3];
  float (*mCFNormal)[4];
  CExtDummy *mDummy;
  CPathFinder mPathFinder;
  int mColFaceId;
  unsigned int mFindPathCnt;
  __int16 mNowPlayerNum;
  unsigned int mStaticVBCnt;
  CVertexBuffer mStaticVertexBuffer[80];
  unsigned int mVBVertexNum[80];
  CIndexBuffer mStaticIndexedBuffer;
  void *mMultiLayerUV;
  void *mMultiLayerST;
  unsigned __int8 *mStaticAlloc;
  unsigned int mStaticAllocSize;
  unsigned __int8 *mExtBspStaticAlloc;
  unsigned int mExtBspStaticAllocSize;
  int mPickPoly;
  unsigned __int8 *mMatGroupCache;
  int mMatGroupCacheSize;
  float mTempCamera[3];
  __int16 mTempSearchOk;
  __int16 mNowLeafNum;
  _BSP_FILE_HEADER mBSPHeader;
  _EXT_BSP_FILE_HEADER mExtBSPHeader;
  CAlpha mAlpha;
};

