#pragma once

#include "IdaCompat.h"

#include "CNetProcess.h"

struct _CLID;
struct _STORAGE_POS_INDIV;
struct _CHRID;

class  CNetWorking
{
public:
  CNetWorking();
  virtual ~CNetWorking();

  _socket *GetSocket(unsigned int dwProID, unsigned int dwSocketIndex);
  void CloseSocket(unsigned int dwProID, unsigned int dwSocketIndex, bool bSlowClose);
  bool SetNetSystem(unsigned int dwUseProcessNum, _NET_TYPE_PARAM *pType, char *szSystemName, char *pszLogPath);
  void Release();
  int Connect(unsigned int dwProID, unsigned int dwSocketIndex, in_addr dwIP, unsigned __int16 wPort);
  void OnLoop();
  void OnLoop_Receipt();
  void ProcessLogFile(unsigned int dwProID, bool bRecv, bool bSend, bool bSystem);
  unsigned int GetCheckRecvTime(unsigned int dwProID, unsigned int dwSocketIndex);

  virtual void UserLoop();
  virtual bool DataAnalysis(
    unsigned int dwProID,
    unsigned int dwClientIndex,
    _MSG_HEADER *pMsgHeader,
    char *pMsg);
  virtual void AcceptClientCheck(unsigned int dwProID, unsigned int dwIndex, unsigned int dwSerial);
  virtual void CloseClientCheck(unsigned int dwProID, unsigned int dwIndex, unsigned int dwSerial);
  virtual bool ExpulsionSocket(unsigned int dwProID, unsigned int dwIndex, unsigned __int8 byReason, void *pvInfo);
  virtual void AnsyncConnectComplete(unsigned int dwProID, unsigned int dwIndex, int nResult);

  char m_szSystemName[128];
  unsigned int m_dwUseProcessNum;
  CLogFile m_LogFile;
  CNetProcess m_Process[4];
  CNetProcess *m_pProcess[4];
  bool m_bUseFG;
  char m_szServerName[33];
  char m_szLogPath[128];
};

class  CNetworkEX : public CNetWorking
{
public:
  unsigned int dwMonsterPosMiss;
  unsigned int dwPlayerPosMiss;
  unsigned __int8 m_byStatus[4];

  void UserLoop() override;
  bool DataAnalysis(
    unsigned int dwProID,
    unsigned int dwClientIndex,
    _MSG_HEADER *pMsgHeader,
    char *pMsg) override;
  void AcceptClientCheck(unsigned int dwProID, unsigned int dwIndex, unsigned int dwSerial) override;
  void CloseClientCheck(unsigned int dwProID, unsigned int dwIndex, unsigned int dwSerial) override;
  bool ExpulsionSocket(unsigned int dwProID, unsigned int dwIndex, unsigned __int8 byReason, void *pvInfo) override;
  void AnsyncConnectComplete(unsigned int dwProID, unsigned int dwIndex, int nResult) override;

  void SetPassablePacket(unsigned int dwProID, unsigned __int8 byHeader1, unsigned __int8 byHeader2);
  void Close(unsigned int dwProID, unsigned int dwSocketIndex, bool bSlowClose, const char *pszLog);

  bool ClientLineAnalysis(unsigned int n, _MSG_HEADER *pMsgHeader, char *pMsg);
  bool AccountLineAnalysis(unsigned int n, _MSG_HEADER *pMsgHeader, char *pMsg);
  bool BillingLineAnalysis(int n, _MSG_HEADER *pMsgHeader, char *pMsg);
  bool WebAgentLineAnalysis(int n, _MSG_HEADER *pMsgHeader, char *pMsg);
  char Apex_R(int n, unsigned __int16 wSize, char *pBuf);
  char Apex_T(int n, unsigned __int16 wSize, char *pBuf);

  bool EnterWorldRequest(unsigned int n, _MSG_HEADER *pMsgHeader, char *pBuf);
  bool MoveLobbyRequest(unsigned int n, char *pBuf);
  bool RegedCharRequest(unsigned int n, char *pBuf);
  bool AddCharRequest(unsigned int n, char *pBuf);
  bool DelCharRequest(unsigned int n, char *pBuf);
  bool SelCharRequest(unsigned int n, char *pBuf);
  bool TutorialProcessReport(int n, char *pBuf);
  bool AliveCharRequest(int n, char *pBuf);
  bool NotifyLocalTimeRequest(int n, char *pBuf);
  bool NewPosStartRequest(unsigned int n, char *pBuf);
  bool BaseDownloadRequest(unsigned int n, char *pBuf);
  bool InvenDownloadRequest(unsigned int n, char *pBuf);
  bool CumDownloadRequest(unsigned int n, char *pBuf);
  bool ForceDownloadRequest(unsigned int n, char *pBuf);
  bool QuestDownloadRequest(unsigned int n, char *pBuf);
  bool SpecialDownloadRequest(unsigned int n, char *pBuf);
  bool OtherShapeRequest(unsigned int n, char *pBuf);
  bool Revival(unsigned int n, char *pBuf);
  bool ExitWorldRequest(unsigned int n, char *pBuf);
  bool LinkBoardDownloadRequest(unsigned int n, char *pBuf);
  bool MacroDownLoadRequest(unsigned int n, char *pBuf);
  bool AMP_DownloadRequest(unsigned int n, char *pBuf);
  bool NextPoint(unsigned int n, char *pBuf);
  bool RealMovPosRequest(unsigned int n, char *pBuf);
  bool Stop(unsigned int n, char *pBuf);
  bool GotoBasePortalRequest(unsigned int n, char *pBuf);
  bool GotoAvatorRequest(unsigned int n, char *pBuf);
  bool MovePortalRequest(unsigned int n, char *pBuf);
  bool RegistBindRequest(unsigned int n, char *pBuf);
  bool EnterReturnGateRequest(unsigned int n, char *pBuf);
  bool MoveTypeChangeRequeset(unsigned int n, char *pBuf);
  bool MoveInfoRequeset(unsigned int n, char *pBuf);
  bool PlayerInfoResult(unsigned int n, char *pBuf);
  bool SelectClassRequest(unsigned int n, char *pBuf);
  bool InitClassRequest(unsigned int n, char *pBuf);
  bool InitClassCostRequest(unsigned int n, char *pBuf);
  bool CanSelectClassRequest(unsigned int n, char *pBuf);
  bool SelectPcBangRewardRequest(unsigned int n, char *pBuf);
  bool BuyStoreRequest(unsigned int n, char *pBuf);
  bool SellStoreRequest(unsigned int n, char *pBuf);
  bool StoreListRequest(unsigned int n, char *pBuf);
  bool ExchangeDalantForGoldRequest(unsigned int n, char *pBuf);
  bool ExchangeGoldForDalantRequest(unsigned int n, char *pBuf);
  bool LimitItemNumRequest(unsigned int n, char *pBuf);
  bool TalikRecorverList(unsigned int n, char *pBuf);
  bool PvpCashRecorverWithTalik(unsigned int n, char *pBuf);
  bool PcBangPrimiumCouponRequest(unsigned int n, char *pBuf);
  bool AttackPersonalRequest(unsigned int n, char *pBuf);
  bool AttackSkillRequest(unsigned int n, char *pBuf);
  bool AttackForceRequest(unsigned int n, char *pBuf);
  bool AttackUnitRequest(unsigned int n, char *pBuf);
  bool AttackTestRequest(unsigned int n, char *pBuf);
  bool AttackSiegeRequest(unsigned int n, char *pBuf);
  bool ItemboxTakeRequest(unsigned int n, char *pBuf);
  bool ThrowStorageRequest(unsigned int n, char *pBuf);
  bool UsePotionRequest(unsigned int n, char *pBuf);
  bool EquipPartRequest(unsigned int n, char *pBuf);
  bool EmbellishRequest(unsigned int n, char *pBuf);
  bool OffPartRequest(unsigned int n, char *pBuf);
  bool MakeItemRequest(unsigned int n, char *pBuf);
  bool UpgradeItemRequest(unsigned int n, char *pBuf);
  bool DownGradeItemRequest(unsigned int n, char *pBuf);
  bool AddBagRequest(unsigned int n, char *pBuf);
  bool UseRecoverLossExpItemRequest(unsigned int n, char *pBuf);
  bool CombineItemRequest(unsigned int n, char *pBuf);
  bool ExchangeItemRequest(unsigned int n, char *pBuf);
  bool CombineExItemRequest(unsigned int n, char *pBuf);
  bool CombineExItemAcceptRequest(unsigned int n, char *pBuf);
  bool UseFireCrackerItemRequest(unsigned int n, char *pBuf);
  bool SetItemCheckRequest(unsigned int n, char *pBuf);
  bool UseSoccerBallItemRequest(unsigned int n, char *pBuf);
  bool UseRadarItemRequest(unsigned int n, char *pBuf);
  bool RadarCharListRequest(unsigned int n, char *pBuf);
  bool NPCLinkCheckItemRequest(unsigned int n, char *pBuf);
  bool UseRecallTeleportItemRequest(unsigned int n, char *pBuf);
  bool CharacterRenameCash(unsigned int n, char *pBuf);
  bool TalikCrystalExchangeRequest(unsigned int n, _MSG_HEADER *pHeader, char *pBuf);

  bool ChatOperatorRequest(unsigned int n, char *pBuf);
  bool ChatCircleRequest(unsigned int n, char *pBuf);
  bool ChatFarRequest(unsigned int n, char *pBuf);
  bool ChatPartyRequest(unsigned int n, char *pBuf);
  bool ChatRaceRequest(unsigned int n, char *pBuf);
  bool ChatCheatRequest(unsigned int n, char *pBuf);
  bool ChatManageRequest(unsigned int n, char *pBuf);
  bool ChatMgrWhisperRequest(unsigned int n, char *pBuf);
  bool ChatMapRecvYesOrNo(unsigned int n, char *pBuf);
  bool ChatMapRequest(unsigned int n, char *pBuf);
  bool ChatRaceBossRequest(unsigned int n, char *pBuf);
  bool ChatGuildEstSenRequest(unsigned int n, char *pBuf);
  bool ChatRePresentationRequest(unsigned int n, char *pBuf);
  bool ChatAllRecvYesOrNo(unsigned int n, char *pBuf);
  bool ChatAllRequest(unsigned int n, char *pBuf);
  bool ChatGreetingMsg_GM(unsigned int n, char *pBuf);
  bool ChatGreetingMsg_RACE(unsigned int n, char *pBuf);
  bool ChatGreetingMsg_GUILD(unsigned int n, char *pBuf);
  bool ChatTradeRequestMsg(unsigned int n, char *pBuf);
  bool ChatGuildRequest(unsigned int n, char *pBuf);
  bool ChatMultiFarRequest(unsigned int n, char *pBuf);
  bool ChatRaceBossCryRequest(unsigned int n, char *pBuf);
  bool ChatGmNoticeRequest(unsigned int n, char *pBuf);

  char ForceInvenChangeRequest(int n, _STORAGE_POS_INDIV *pBuf);
  char AnimusInvenChangeRequest(int n, _STORAGE_POS_INDIV *pBuf);
  char ResSeparationRequest(int n, char *pBuf);
  char ResDivisionRequest(int n, char *pBuf);
  char PotionSocketSeparationRequest(int n, char *pBuf);
  char PotionSocketDivisionRequest(int n, char *pBuf);
  char AlterItemSlotRequest(int n, char *pBuf);
  char AlterLinkBoardSlotRequest(int n, char *pBuf);
  char PvpRankListRequest(int n, char *pBuf);
  char ModeChangeRequest(int n, char *pBuf);
  char GustureRequest(int n, char *pBuf);
  char AlterWindowInfoRequest(int n, char *pBuf);
  char SetTargetObjectRequest(int n, char *pBuf);
  char ReleaseTargetObjectRequest(int n, char *pBuf);
  char PartyReqBlockReport(int n, bool *pBuf);
  char WhisperBlockReport(int n, bool *pBuf);
  char TradeBlockReport(int n, bool *pBuf);
  char GuildBattleBlockReport(int n, bool *pBuf);
  char PlayerMacroUpdate(int n, char *pBuf);
  char TotalGuildRankRequest(int n, char *pBuf);
  char WeeklyGuildRankRequest(int n, char *pBuf);
  char SetRaceBossCryMsgRequest(int n, char *pBuf);
  char NotifyRaceBossCryMsg(int n, char *pBuf);
  char SetGroupTargetObjectRequest(int n, char *pBuf);
  char ReleaseGroupTargetObjectRequest(int n, char *pBuf);
  char SetGroupMapPointRequest(int n, char *pBuf);
  char RequestPatriarchPunishment(int n, char *pBuf);
  char RequestTaxRate(int n, char *pBuf);
  char RequestChangeTaxRate(int n, char *pBuf);
  char RequestUILockInit(int n, char *pBuf);
  char RequestUILockUserCertify(int n, char *pBuf);
  char RequestUILockUpdateInfo(int n, char *pBuf);
  char RequestUILockFindPW(int n, char *pBuf);
  char RequestTLLogoutTime(int n, char *pBuf);
  char MineStartRequest(int n, char *pBuf);
  char MineCancleRequest(int n, char *pBuf);
  char ResCuttingRequest(int n, char *pBuf);
  char OreIntoBagRequest(int n, char *pBuf);
  char CuttingCompleteRequest(int n, char *pBuf);
  char PartyJoinInvitation(int n, char *pBuf);
  char PartyJoinInvitationAnswer(int n, _CLID *pBuf);
  char PartyJoinApplication(int n, char *pBuf);
  char PartyJoinApplicatiohAnswer(int n, _CLID *pBuf);
  char PartyLeaveSelfRequest(int n, char *pBuf);
  char PartyLeaveCompulsionRequest(int n, char *pBuf);
  char PartyDisjointRequest(int n, char *pBuf);
  char PartySuccessionRequest(int n, char *pBuf);
  char PartyLockRequest(int n, bool *pBuf);
  char AlterPartyLootShareRequest(int n, char *pBuf);
  char AwayPartyInvitation(int n, char *pBuf);
  char AwayPartyInvitationAnswer(int n, char *pBuf);
  char ForceRequest(int n, char *pBuf);
  char SkillRequest(int n, char *pBuf);
  char ClassSkillRequest(int n, char *pBuf);
  char SkillRecallTeleportRequest(int n, char *pBuf);
  char ClassSkillRecallTeleportRequest(int n, char *pBuf);
  char ThrowSkillRequest(int n, char *pBuf);
  char ThrowUnitRequest(int n, _CHRID *pBuf);
  char MakeTowerRequest(int n, char *pBuf);
  char BackTowerRequest(int n, char *pBuf);
  char MakeTrapRequest(int n, char *pBuf);
  char BackTrapRequest(int n, char *pBuf);
  char DecideRecallRequest(int n, char *pBuf);
  char ForceRecallTeleportRequest(int n, char *pBuf);
  char MoveToOwnStoneMapRequest(int n, char *pBuf);
  char DTradeAskRequest(int n, char *pBuf);
  char DTradeAnswerRequest(int n, _CLID *pBuf);
  char DTradeCancleRequest(int n, char *pBuf);
  char DTradeLockRequest(int n, char *pBuf);
  char DTradeAddRequest(int n, char *pBuf);
  char DTradeDelRequest(int n, char *pBuf);
  char DTradeBetRequest(int n, char *pBuf);
  char DTradeOKRequest(int n, char *pBuf);
  char ObjectServerPosRequest(unsigned int n, char *pBuf);
  char AnimusRecallRequest(int n, char *pBuf);
  char AnimusReturnRequest(int n, char *pBuf);
  char AnimusCommandRequest(int n, char *pBuf);
  char AnimusTargetRequest(int n, char *pBuf);
  char UnitFrameBuyRequest(int n, char *pBuf);
  char UnitSellRequest(int n, char *pBuf);
  char UnitPartTuningRequest(int n, char *pBuf);
  char UnitFrameRepairRequest(int n, char *pBuf);
  char UnitBulletFillRequest(int n, char *pBuf);
  char UnitPackFillRequest(int n, char *pBuf);
  char UnitDeliveryRequest(int n, char *pBuf);
  char UnitReturnRequest(int n, char *pBuf);
  char UnitTakeRequest(int n, char *pBuf);
  char UnitLeaveRequest(int n, char *pBuf);
  char UnitBulletReplaceRequest(int n, char *pBuf);
  char SelectWaitedQuestReport(int n, char *pBuf);
  char QuestSelectRewardReport(int n, char *pBuf);
  char NPCDialogRequest(int n, char *pBuf);
  char NPCWatchingRequest(int n, char *pBuf);
  char NPCQuestListRequest(int n, char *pBuf);
  char NPCQuestRequest(int n, char *pBuf);
  char QuestGiveupRequest(int n, char *pBuf);
  char BriefPassReport(int n, char *pBuf);
  char CastVoteRequest(int n, char *pBuf);
  char ProposeVoteRequest(int n, char *pBuf);
  char GuildEstablishRequest(int n, char *pBuf);
  char GuildDownloadRequest(int n, char *pBuf);
  char GuildJoinApplyRequest(int n, char *pBuf);
  char GuildJoinApplyCancelRequest(int n, char *pBuf);
  char GuildJoinAcceptRequest(int n, char *pBuf);
  char GuildSelfLeaveRequest(int n, char *pBuf);
  char GuildOfferSuggestRequest(int n, char *pBuf);
  char GuildCancelSuggestRequest(int n, char *pBuf);
  char GuildVoteRequest(int n, char *pBuf);
  char GuildQueryInfoRequest(int n, char *pBuf);
  char GuildPushMoneyRequest(int n, char *pBuf);
  char GuildBattlePossibleGuildBattleList(int n, char *pBuf);
  char GuildBattleRankListRequest(int n, char *pBuf);
  char GuildBattleJoinGuildBattleRequest(int n, char *pBuf);
  char GuildBattleReservedScheduleRequest(int n, char *pBuf);
  char GuildBattleCurrentBattleInfoRequest(int n, char *pBuf);
  char GuildBattleTakeGravityStoneRequest(int n, char *pBuf);
  char GuildBattleGetGravityStoneRequest(int n, char *pBuf);
  char GuildBattleGoalRequest(int n, char *pBuf);
  char GuildRoomRentRequest(int n, char *pBuf);
  char GuildRoomEnterRequest(int n, char *pBuf);
  char GuildRoomOutRequest(int n, char *pBuf);
  char GuildRoomRestTimeRequest(int n, char *pBuf);
  char GuildHonorListRequest(int n, char *pBuf);
  char GuildSetHonorRequest(int n, char *pBuf);
  char GuildListRequest(int n, char *pBuf);
  char GuildNextHonorListRequest(int n, char *pBuf);
  char GuildManageRequest(int n, char *pBuf);
  char TransformSiegeModeRequest(int n, char *pBuf);
  char ReleaseSiegeModeRequest(int n, char *pBuf);
  char BillingInfoRequest(int n, char *pBuf);
  char ATradeRegItemRequest(int n, char *pBuf);
  char ATradeAdjustPriceRequest(int n, char *pBuf);
  char ATradeClearItemRequest(int n, char *pBuf);
  char ATradeTaxRateRequest(int n, char *pBuf);
  char ATradeBuyItemRequest(int n, char *pBuf);
  char ATradeRegedListRequest(int n, char *pBuf);
  char ATradeReRegistRequest(int n, char *pBuf);
  char BuddyDownloadRequest(int n, char *pBuf);
  char BuddyAddRequest(int n, char *pBuf);
  char BuddyAddAnswer(int n, char *pBuf);
  char BuddyDelRequest(int n, char *pBuf);
  char TransShipRenewTicketRequest(int n, char *pBuf);
  char TrunkEstRequest(int n, char *pBuf);
  char TrunkDownloadRequest(int n, char *pBuf);
  char TrunkChangePasswdRequest(int n, char *pBuf);
  char TrunkExtendRequest(int n, char *pBuf);
  char TrunkAlterItemSlotRequest(int n, char *pBuf);
  char TrunkResDivisionRequest(int n, char *pBuf);
  char TrunkPotionDivisionRequest(int n, char *pBuf);
  char TrunkIoMoveRequest(int n, char *pBuf);
  char TrunkIoSwapRequest(int n, char *pBuf);
  char TrunkIoMergeRequest(int n, char *pBuf);
  char TrunkIoMoneyRequest(int n, char *pBuf);
  char TrunkPwHintIndexRequest(int n, char *pBuf);
  char TrunkHintAnswerRequest(int n, char *pBuf);
  char TrunkCreateCostIsFreeRequest(int n, char *pBuf);
  char DarkHoleOpenRequest(int n, char *pBuf);
  char DarkHoleEnterRequest(int n, char *pBuf);
  char DarkHoleGiveupOutRequest(int n, char *pBuf);
  char DarkHoleClearOutRequest(int n, char *pBuf);
  char DarkHoleAnswerReenterRequest(int n, char *pBuf);
  char BossSMSMsgRequest(int n, char *pBuf);
  char PostSendRequest(int n, char *pBuf);
  char PostListRequest(int n, char *pBuf);
  char PostContentRequest(int n, char *pBuf);
  char PostItemGoldRequest(int n, char *pBuf);
  char PostDeleteRequest(int n, char *pBuf);
  char PostReturnConfirmRequest(int n, char *pBuf);

  bool OpenWorldSuccessResult(unsigned int n, char *pMsg);
  bool OpenWorldFailureResult(unsigned int n, char *pMsg);
  bool ForceCloseCommand(unsigned int n, _CLID *pMsg);
  bool TransAccountInform(unsigned int n, char *pMsg);
  bool EnterWorldResult(unsigned int n, _CLID *pMsg);
  bool UILockInitResult(unsigned int n, char *pMsg);
  bool UILockUpdateResult(unsigned int n, char *pMsg);
  bool UILockRefreshResult(unsigned int n, char *pMsg);
  bool CheckIsBlockIPResult(unsigned int n, char *pMsg);
  bool ConEventTotalSalesCheck(int n, char *pBuf);
  bool DisconnectGuildWarCharacterRequest(int n, char *pBuf);
  bool ManageClientLimitRunRequest(char *pBuf);
  bool ManageClientForceExitRequest();
  bool CashDBInfoRecvResult(int n, char *pBuf);
  bool WorldServiceInform(unsigned int n, bool *pMsg);
  bool WorldExitInform(unsigned int n, char *pMsg);
  bool WorldMsgInform(unsigned int n, char *pMsg);
  bool ChatLockCommand(unsigned int n, _CLID *pMsg);

  bool BillingCloseRequest(int n, char *pBuf);
  bool BillingRemaintimePersonal(int n, char *pBuf);
  bool BillingRemaintimePCBang(int n, char *pBuf);
  bool BillingChangeType(int n, char *pBuf);
  bool BillingExpirePersonal(int n, char *pBuf);
  bool BillingExpirePCBang(int n, char *pBuf);
  bool BillingExpireIPOverflow(int n, char *pBuf);
  bool BillingDestroyModule(int n, char *pBuf);
  bool TaiwanBillingUserCertify(int n, char *pBuf);
  bool ChinaBillingChangePrimium(int n, char *pBuf);
  bool ZoneAliveCheckRequest(int n, char *pBuf);

  bool LogInWebAgentServer(unsigned int n, char *pBuf);
  bool SendRaceBossMsgFromWebRequest(int n, char *pBuf);
  bool LogInControllServer(unsigned int n, char *pBuf);
  bool CancelRaceBossSMSMsg(int n, char *pBuf);
  bool ConnectionStatusRequest(int n);
};

extern CNetworkEX g_Network;

void DeCrypt_Move(char *pStr, int nSize, unsigned __int8 byPlus, unsigned __int16 wCryptKey);

