#pragma once

#include "IdaCompat.h"

#include "CNetProcess.h"

struct _CLID;
struct _billing_close_request_bizo;
struct _cashdb_info_recv_result_acwr;
struct _change_type_request_bizo;
struct _chat_lock_command_acwr;
struct _check_is_block_ip_result_acwr;
struct _d_trade_answer_request_clzo;
struct _disconnect_guild_war_character_request_acwr;
struct _enter_world_result_acwr;
struct _equip_part_request_clzo;
struct _expire_ipoverflow_request_bizo;
struct _expire_pcbang_request_bizo;
struct _expire_personal_request_bizo;
struct _force_close_command_acwr;
struct _goto_avator_request_clzo;
struct _guild_battle_block_report_clzo;
struct _guild_establish_request_clzo;
struct _guild_join_apply_request_clzo;
struct _init_class_request_clzo;
struct _login_controll_server_request_wazo;
struct _login_web_agent_server_request_wazo;
struct _manage_client_limit_run_request_acwr;
struct _new_pos_start_request_clzo;
struct _off_part_request_clzo;
struct _open_control_inform_acwr;
struct _open_world_failure_acwr;
struct _open_world_success_acwr;
struct _party_join_application_answer_clzo;
struct _party_join_invitation_answer_clzo;
struct _party_lock_request_clzo;
struct _party_req_block_report_clzo;
struct _remaintime_pcbang_request_bizo;
struct _remaintime_personal_request_bizo;
struct _send_race_boss_msg_from_web_request_wazo;
struct _throw_storage_request_clzo;
struct _trans_account_inform_acwr;
struct _trade_block_report_clzo;
struct _trunk_hint_answer_request_clzo;
struct _uilock_init_result_acwr;
struct _uilock_update_result_acwr;
struct _uilock_user_refresh_info_result_acwr;
struct _use_recall_teleport_item_request_clzo;
struct _user_block_result_acwr;
struct _whisper_block_report_clzo;
struct _world_msg_inform_acwr;
struct _world_service_inform_acwr;
struct _zone_alive_check_request_bizo;
struct _away_party_invitation_request_clzo;

class  CNetWorking
{
public:
  CNetWorking();
  virtual ~CNetWorking();

  _socket *GetSocket(unsigned int dwProID, unsigned int dwSocketIndex);
  void CloseSocket(unsigned int dwProID, unsigned int dwSocketIndex, bool bSlowClose);
  bool SetNetSystem(unsigned int dwUseProcessNum, _NET_TYPE_PARAM *pType, char *szSystemName, char *pszLogPath);
  void Release();
  int Connect(unsigned int dwProID, unsigned int dwSocketIndex, in_addr dwIP, unsigned __int16 wPort);
  void OnLoop();
  void OnLoop_Receipt();
  void ProcessLogFile(unsigned int dwProID, bool bRecv, bool bSend, bool bSystem);
  unsigned int GetCheckRecvTime(unsigned int dwProID, unsigned int dwSocketIndex);

  virtual void UserLoop();
  virtual bool DataAnalysis(
    unsigned int dwProID,
    unsigned int dwClientIndex,
    _MSG_HEADER *pMsgHeader,
    char *pMsg);
  virtual void AcceptClientCheck(unsigned int dwProID, unsigned int dwIndex, unsigned int dwSerial);
  virtual void CloseClientCheck(unsigned int dwProID, unsigned int dwIndex, unsigned int dwSerial);
  virtual bool ExpulsionSocket(unsigned int dwProID, unsigned int dwIndex, unsigned __int8 byReason, void *pvInfo);
  virtual void AnsyncConnectComplete(unsigned int dwProID, unsigned int dwIndex, int nResult);

  char m_szSystemName[128];
  unsigned int m_dwUseProcessNum;
  CLogFile m_LogFile;
  CNetProcess m_Process[4];
  CNetProcess *m_pProcess[4];
  bool m_bUseFG;
  char m_szServerName[33];
  char m_szLogPath[128];
};

class  CNetworkEX : public CNetWorking
{
public:
  CNetworkEX();
  ~CNetworkEX() override;

  unsigned int dwMonsterPosMiss;
  unsigned int dwPlayerPosMiss;
  unsigned __int8 m_byStatus[4];

  void UserLoop() override;
  bool DataAnalysis(
    unsigned int dwProID,
    unsigned int dwClientIndex,
    _MSG_HEADER *pMsgHeader,
    char *pMsg) override;
  void AcceptClientCheck(unsigned int dwProID, unsigned int dwIndex, unsigned int dwSerial) override;
  void CloseClientCheck(unsigned int dwProID, unsigned int dwIndex, unsigned int dwSerial) override;
  bool ExpulsionSocket(unsigned int dwProID, unsigned int dwIndex, unsigned __int8 byReason, void *pvInfo) override;
  void AnsyncConnectComplete(unsigned int dwProID, unsigned int dwIndex, int nResult) override;

  void SetPassablePacket(unsigned int dwProID, unsigned __int8 byHeader1, unsigned __int8 byHeader2);
  void Close(unsigned int dwProID, unsigned int dwSocketIndex, bool bSlowClose, const char *pszLog);

  bool ClientLineAnalysis(unsigned int n, _MSG_HEADER *pMsgHeader, char *pMsg);
  bool AccountLineAnalysis(unsigned int n, _MSG_HEADER *pMsgHeader, char *pMsg);
  bool BillingLineAnalysis(int n, _MSG_HEADER *pMsgHeader, char *pMsg);
  bool WebAgentLineAnalysis(int n, _MSG_HEADER *pMsgHeader, char *pMsg);
  bool Apex_R(int n, unsigned __int16 wSize, char *pBuf);
  bool Apex_T(int n, unsigned __int16 wSize, char *pBuf);

  bool EnterWorldRequest(unsigned int n, _MSG_HEADER *pMsgHeader, char *pBuf);
  bool MoveLobbyRequest(unsigned int n, char *pBuf);
  bool RegedCharRequest(unsigned int n, char *pBuf);
  bool AddCharRequest(unsigned int n, char *pBuf);
  bool DelCharRequest(unsigned int n, char *pBuf);
  bool SelCharRequest(unsigned int n, char *pBuf);
  bool TutorialProcessReport(int n, char *pBuf);
  bool AliveCharRequest(int n, char *pBuf);
  bool NotifyLocalTimeRequest(int n, char *pBuf);
  bool NewPosStartRequest(unsigned int n, const _new_pos_start_request_clzo *request);
  bool BaseDownloadRequest(unsigned int n, char *pBuf);
  bool InvenDownloadRequest(unsigned int n, char *pBuf);
  bool CumDownloadRequest(unsigned int n, char *pBuf);
  bool ForceDownloadRequest(unsigned int n, char *pBuf);
  bool QuestDownloadRequest(unsigned int n, char *pBuf);
  bool SpecialDownloadRequest(unsigned int n, char *pBuf);
  bool OtherShapeRequest(unsigned int n, char *pBuf);
  bool Revival(unsigned int n, char *pBuf);
  bool ExitWorldRequest(unsigned int n, char *pBuf);
  bool LinkBoardDownloadRequest(unsigned int n, char *pBuf);
  bool MacroDownLoadRequest(unsigned int n, char *pBuf);
  bool AMP_DownloadRequest(unsigned int n, char *pBuf);
  bool NextPoint(unsigned int n, char *pBuf);
  bool RealMovPosRequest(unsigned int n, char *pBuf);
  bool Stop(unsigned int n, char *pBuf);
  bool GotoBasePortalRequest(unsigned int n, char *pBuf);
  bool GotoAvatorRequest(unsigned int n, const _goto_avator_request_clzo *request);
  bool MovePortalRequest(unsigned int n, char *pBuf);
  bool RegistBindRequest(unsigned int n, char *pBuf);
  bool EnterReturnGateRequest(unsigned int n, char *pBuf);
  bool MoveTypeChangeRequeset(unsigned int n, char *pBuf);
  bool MoveInfoRequeset(unsigned int n, char *pBuf);
  bool PlayerInfoResult(unsigned int n, char *pBuf);
  bool SelectClassRequest(unsigned int n, char *pBuf);
  bool InitClassRequest(unsigned int n, const _init_class_request_clzo *request);
  bool InitClassCostRequest(unsigned int n, char *pBuf);
  bool CanSelectClassRequest(unsigned int n, char *pBuf);
  bool SelectPcBangRewardRequest(unsigned int n, char *pBuf);
  bool BuyStoreRequest(unsigned int n, char *pBuf);
  bool SellStoreRequest(unsigned int n, char *pBuf);
  bool StoreListRequest(unsigned int n, char *pBuf);
  bool ExchangeDalantForGoldRequest(unsigned int n, char *pBuf);
  bool ExchangeGoldForDalantRequest(unsigned int n, char *pBuf);
  bool ExchangeGoldForPvPRequest(int n, char *pBuf);
  bool OpenControlInform(unsigned int n, const _open_control_inform_acwr *request);
  bool UserBlockResult(unsigned int n, const _user_block_result_acwr *request);
  bool LimitItemNumRequest(unsigned int n, char *pBuf);
  bool TalikRecorverList(unsigned int n, char *pBuf);
  bool PvpCashRecorverWithTalik(unsigned int n, char *pBuf);
  bool PcBangPrimiumCouponRequest(unsigned int n, char *pBuf);
  bool AttackPersonalRequest(unsigned int n, char *pBuf);
  bool AttackSkillRequest(unsigned int n, char *pBuf);
  bool AttackForceRequest(unsigned int n, char *pBuf);
  bool AttackUnitRequest(unsigned int n, char *pBuf);
  bool AttackTestRequest(unsigned int n, char *pBuf);
  bool AttackSiegeRequest(unsigned int n, char *pBuf);
  bool ItemboxTakeRequest(unsigned int n, char *pBuf);
  bool ThrowStorageRequest(unsigned int n, _throw_storage_request_clzo *request);
  bool UsePotionRequest(unsigned int n, char *pBuf);
  bool EquipPartRequest(unsigned int n, _equip_part_request_clzo *request);
  bool EmbellishRequest(unsigned int n, char *pBuf);
  bool OffPartRequest(unsigned int n, _off_part_request_clzo *request);
  bool MakeItemRequest(unsigned int n, char *pBuf);
  bool UpgradeItemRequest(unsigned int n, char *pBuf);
  bool DownGradeItemRequest(unsigned int n, char *pBuf);
  bool AddBagRequest(unsigned int n, char *pBuf);
  bool UseRecoverLossExpItemRequest(unsigned int n, char *pBuf);
  bool CombineItemRequest(unsigned int n, char *pBuf);
  bool ExchangeItemRequest(unsigned int n, char *pBuf);
  bool CombineExItemRequest(unsigned int n, char *pBuf);
  bool CombineExItemAcceptRequest(unsigned int n, char *pBuf);
  bool UseFireCrackerItemRequest(unsigned int n, char *pBuf);
  bool SetItemCheckRequest(unsigned int n, char *pBuf);
  bool UseSoccerBallItemRequest(unsigned int n, char *pBuf);
  bool UseRadarItemRequest(unsigned int n, char *pBuf);
  bool RadarCharListRequest(unsigned int n, char *pBuf);
  bool NPCLinkCheckItemRequest(unsigned int n, char *pBuf);
  bool UseRecallTeleportItemRequest(unsigned int n, _use_recall_teleport_item_request_clzo *request);
  bool CharacterRenameCash(unsigned int n, char *pBuf);
  bool TalikCrystalExchangeRequest(unsigned int n, _MSG_HEADER *pHeader, char *pBuf);

  bool ChatOperatorRequest(unsigned int n, char *pBuf);
  bool ChatCircleRequest(unsigned int n, char *pBuf);
  bool ChatFarRequest(unsigned int n, char *pBuf);
  bool ChatPartyRequest(unsigned int n, char *pBuf);
  bool ChatRaceRequest(unsigned int n, char *pBuf);
  bool ChatCheatRequest(unsigned int n, char *pBuf);
  bool ChatManageRequest(unsigned int n, char *pBuf);
  bool ChatMgrWhisperRequest(unsigned int n, char *pBuf);
  bool ChatMapRecvYesOrNo(unsigned int n, char *pBuf);
  bool ChatMapRequest(unsigned int n, char *pBuf);
  bool ChatRaceBossRequest(unsigned int n, char *pBuf);
  bool ChatGuildEstSenRequest(unsigned int n, char *pBuf);
  bool ChatRePresentationRequest(unsigned int n, char *pBuf);
  bool ChatAllRecvYesOrNo(unsigned int n, char *pBuf);
  bool ChatAllRequest(unsigned int n, char *pBuf);
  bool ChatGreetingMsg_GM(unsigned int n, char *pBuf);
  bool ChatGreetingMsg_RACE(unsigned int n, char *pBuf);
  bool ChatGreetingMsg_GUILD(unsigned int n, char *pBuf);
  bool ChatTradeRequestMsg(unsigned int n, char *pBuf);
  bool ChatGuildRequest(unsigned int n, char *pBuf);
  bool ChatMultiFarRequest(unsigned int n, char *pBuf);
  bool ChatRaceBossCryRequest(unsigned int n, char *pBuf);
  bool ChatGmNoticeRequest(unsigned int n, char *pBuf);

  bool ForceInvenChangeRequest(int n, char *pBuf);
  bool AnimusInvenChangeRequest(int n, char *pBuf);
  bool ResSeparationRequest(int n, char *pBuf);
  bool ResDivisionRequest(int n, char *pBuf);
  bool PotionSocketSeparationRequest(int n, char *pBuf);
  bool PotionSocketDivisionRequest(int n, char *pBuf);
  bool AlterItemSlotRequest(int n, char *pBuf);
  bool AlterLinkBoardSlotRequest(int n, char *pBuf);
  bool PvpRankListRequest(int n, char *pBuf);
  bool ModeChangeRequest(int n, char *pBuf);
  bool GustureRequest(int n, char *pBuf);
  bool AlterWindowInfoRequest(int n, char *pBuf);
  bool SetTargetObjectRequest(int n, char *pBuf);
  bool ReleaseTargetObjectRequest(int n, char *pBuf);
  bool PartyReqBlockReport(int n, const _party_req_block_report_clzo *request);
  bool WhisperBlockReport(int n, const _whisper_block_report_clzo *request);
  bool TradeBlockReport(int n, const _trade_block_report_clzo *request);
  bool GuildBattleBlockReport(int n, const _guild_battle_block_report_clzo *request);
  bool PlayerMacroUpdate(int n, char *pBuf);
  bool TotalGuildRankRequest(int n, char *pBuf);
  bool WeeklyGuildRankRequest(int n, char *pBuf);
  bool SetRaceBossCryMsgRequest(int n, char *pBuf);
  bool NotifyRaceBossCryMsg(int n, char *pBuf);
  bool SetGroupTargetObjectRequest(int n, char *pBuf);
  bool ReleaseGroupTargetObjectRequest(int n, char *pBuf);
  bool SetGroupMapPointRequest(int n, char *pBuf);
  bool RequestPatriarchPunishment(int n, char *pBuf);
  bool RequestTaxRate(int n, char *pBuf);
  bool RequestChangeTaxRate(int n, char *pBuf);
  bool RequestUILockInit(int n, char *pBuf);
  bool RequestUILockUserCertify(int n, char *pBuf);
  bool RequestUILockUpdateInfo(int n, char *pBuf);
  bool RequestUILockFindPW(int n, char *pBuf);
  bool RequestTLLogoutTime(int n, char *pBuf);
  bool MineStartRequest(int n, char *pBuf);
  bool MineCancleRequest(int n, char *pBuf);
  bool ResCuttingRequest(int n, char *pBuf);
  bool OreIntoBagRequest(int n, char *pBuf);
  bool CuttingCompleteRequest(int n, char *pBuf);
  bool PartyJoinInvitation(int n, char *pBuf);
  bool PartyJoinInvitationAnswer(int n, _party_join_invitation_answer_clzo *request);
  bool PartyJoinApplication(int n, char *pBuf);
  bool PartyJoinApplicatiohAnswer(int n, _party_join_application_answer_clzo *request);
  bool PartyLeaveSelfRequest(int n, char *pBuf);
  bool PartyLeaveCompulsionRequest(int n, char *pBuf);
  bool PartyDisjointRequest(int n, char *pBuf);
  bool PartySuccessionRequest(int n, char *pBuf);
  bool PartyLockRequest(int n, const _party_lock_request_clzo *request);
  bool AlterPartyLootShareRequest(int n, char *pBuf);
  bool AwayPartyInvitation(int n, const _away_party_invitation_request_clzo *request);
  bool AwayPartyInvitationAnswer(int n, char *pBuf);
  bool ForceRequest(int n, char *pBuf);
  bool SkillRequest(int n, char *pBuf);
  bool ClassSkillRequest(int n, char *pBuf);
  bool SkillRecallTeleportRequest(int n, char *pBuf);
  bool ClassSkillRecallTeleportRequest(int n, char *pBuf);
  bool ThrowSkillRequest(int n, char *pBuf);
  bool ThrowUnitRequest(int n, char *pBuf);
  bool MakeTowerRequest(int n, char *pBuf);
  bool BackTowerRequest(int n, char *pBuf);
  bool MakeTrapRequest(int n, char *pBuf);
  bool BackTrapRequest(int n, char *pBuf);
  bool DecideRecallRequest(int n, char *pBuf);
  bool ForceRecallTeleportRequest(int n, char *pBuf);
  bool MoveToOwnStoneMapRequest(int n, char *pBuf);
  bool DTradeAskRequest(int n, char *pBuf);
  bool DTradeAnswerRequest(int n, _d_trade_answer_request_clzo *request);
  bool DTradeCancleRequest(int n, char *pBuf);
  bool DTradeLockRequest(int n, char *pBuf);
  bool DTradeAddRequest(int n, char *pBuf);
  bool DTradeDelRequest(int n, char *pBuf);
  bool DTradeBetRequest(int n, char *pBuf);
  bool DTradeOKRequest(int n, char *pBuf);
  bool ObjectServerPosRequest(unsigned int n, char *pBuf);
  bool AnimusRecallRequest(int n, char *pBuf);
  bool AnimusReturnRequest(int n, char *pBuf);
  bool AnimusCommandRequest(int n, char *pBuf);
  bool AnimusTargetRequest(int n, char *pBuf);
  bool UnitFrameBuyRequest(int n, char *pBuf);
  bool UnitSellRequest(int n, char *pBuf);
  bool UnitPartTuningRequest(int n, char *pBuf);
  bool UnitFrameRepairRequest(int n, char *pBuf);
  bool UnitBulletFillRequest(int n, char *pBuf);
  bool UnitPackFillRequest(int n, char *pBuf);
  bool UnitDeliveryRequest(int n, char *pBuf);
  bool UnitReturnRequest(int n, char *pBuf);
  bool UnitTakeRequest(int n, char *pBuf);
  bool UnitLeaveRequest(int n, char *pBuf);
  bool UnitBulletReplaceRequest(int n, char *pBuf);
  bool SelectWaitedQuestReport(int n, char *pBuf);
  bool QuestSelectRewardReport(int n, char *pBuf);
  bool NPCDialogRequest(int n, char *pBuf);
  bool NPCWatchingRequest(int n, char *pBuf);
  bool NPCQuestListRequest(int n, char *pBuf);
  bool NPCQuestRequest(int n, char *pBuf);
  bool QuestGiveupRequest(int n, char *pBuf);
  bool BriefPassReport(int n, char *pBuf);
  bool CastVoteRequest(int n, char *pBuf);
  bool ProposeVoteRequest(int n, char *pBuf);
  bool GuildEstablishRequest(int n, const _guild_establish_request_clzo *request);
  bool GuildDownloadRequest(int n, char *pBuf);
  bool GuildJoinApplyRequest(int n, const _guild_join_apply_request_clzo *request);
  bool GuildJoinApplyCancelRequest(int n, char *pBuf);
  bool GuildJoinAcceptRequest(int n, char *pBuf);
  bool GuildSelfLeaveRequest(int n, char *pBuf);
  bool GuildOfferSuggestRequest(int n, char *pBuf);
  bool GuildCancelSuggestRequest(int n, char *pBuf);
  bool GuildVoteRequest(int n, char *pBuf);
  bool GuildQueryInfoRequest(int n, char *pBuf);
  bool GuildPushMoneyRequest(int n, char *pBuf);
  bool GuildBattlePossibleGuildBattleList(int n, char *pBuf);
  bool GuildBattleRankListRequest(int n, char *pBuf);
  bool GuildBattleJoinGuildBattleRequest(int n, char *pBuf);
  bool GuildBattleReservedScheduleRequest(int n, char *pBuf);
  bool GuildBattleCurrentBattleInfoRequest(int n, char *pBuf);
  bool GuildBattleTakeGravityStoneRequest(int n, char *pBuf);
  bool GuildBattleGetGravityStoneRequest(int n, char *pBuf);
  bool GuildBattleGoalRequest(int n, char *pBuf);
  bool GuildRoomRentRequest(int n, char *pBuf);
  bool GuildRoomEnterRequest(int n, char *pBuf);
  bool GuildRoomOutRequest(int n, char *pBuf);
  bool GuildRoomRestTimeRequest(int n, char *pBuf);
  bool GuildHonorListRequest(int n, char *pBuf);
  bool GuildSetHonorRequest(int n, char *pBuf);
  bool GuildListRequest(int n, char *pBuf);
  bool GuildNextHonorListRequest(int n, char *pBuf);
  bool GuildManageRequest(int n, char *pBuf);
  bool TransformSiegeModeRequest(int n, char *pBuf);
  bool ReleaseSiegeModeRequest(int n, char *pBuf);
  bool BillingInfoRequest(int n, char *pBuf);
  bool ATradeRegItemRequest(int n, char *pBuf);
  bool ATradeAdjustPriceRequest(int n, char *pBuf);
  bool ATradeClearItemRequest(int n, char *pBuf);
  bool ATradeTaxRateRequest(int n, char *pBuf);
  bool ATradeBuyItemRequest(int n, char *pBuf);
  bool ATradeRegedListRequest(int n, char *pBuf);
  bool ATradeReRegistRequest(int n, char *pBuf);
  bool BuddyDownloadRequest(int n, char *pBuf);
  bool BuddyAddRequest(int n, char *pBuf);
  bool BuddyAddAnswer(int n, char *pBuf);
  bool BuddyDelRequest(int n, char *pBuf);
  bool TransShipRenewTicketRequest(int n, char *pBuf);
  bool TrunkEstRequest(int n, char *pBuf);
  bool TrunkDownloadRequest(int n, char *pBuf);
  bool TrunkChangePasswdRequest(int n, char *pBuf);
  bool TrunkExtendRequest(int n, char *pBuf);
  bool TrunkAlterItemSlotRequest(int n, char *pBuf);
  bool TrunkResDivisionRequest(int n, char *pBuf);
  bool TrunkPotionDivisionRequest(int n, char *pBuf);
  bool TrunkIoMoveRequest(int n, char *pBuf);
  bool TrunkIoSwapRequest(int n, char *pBuf);
  bool TrunkIoMergeRequest(int n, char *pBuf);
  bool TrunkIoMoneyRequest(int n, char *pBuf);
  bool TrunkPwHintIndexRequest(int n, char *pBuf);
  bool TrunkHintAnswerRequest(int n, const _trunk_hint_answer_request_clzo *request);
  bool TrunkCreateCostIsFreeRequest(int n, char *pBuf);
  bool DarkHoleOpenRequest(int n, char *pBuf);
  bool DarkHoleEnterRequest(int n, char *pBuf);
  bool DarkHoleGiveupOutRequest(int n, char *pBuf);
  bool DarkHoleClearOutRequest(int n, char *pBuf);
  bool DarkHoleAnswerReenterRequest(int n, char *pBuf);
  bool BossSMSMsgRequest(int n, char *pBuf);
  bool PostSendRequest(int n, char *pBuf);
  bool PostListRequest(int n, char *pBuf);
  bool PostContentRequest(int n, char *pBuf);
  bool PostItemGoldRequest(int n, char *pBuf);
  bool PostDeleteRequest(int n, char *pBuf);
  bool PostReturnConfirmRequest(int n, char *pBuf);

  bool OpenWorldSuccessResult(unsigned int n, const _open_world_success_acwr *request);
  bool OpenWorldFailureResult(unsigned int n, const _open_world_failure_acwr *request);
  bool ForceCloseCommand(unsigned int n, const _force_close_command_acwr *request);
  bool TransAccountInform(unsigned int n, const _trans_account_inform_acwr *request);
  bool EnterWorldResult(unsigned int n, const _enter_world_result_acwr *request);
  bool UILockInitResult(unsigned int n, const _uilock_init_result_acwr *request);
  bool UILockUpdateResult(unsigned int n, const _uilock_update_result_acwr *request);
  bool UILockRefreshResult(unsigned int n, const _uilock_user_refresh_info_result_acwr *request);
  bool CheckIsBlockIPResult(unsigned int n, const _check_is_block_ip_result_acwr *request);
  bool ConEventTotalSalesCheck(int n);
  bool DisconnectGuildWarCharacterRequest(int n, const _disconnect_guild_war_character_request_acwr *request);
  bool ManageClientLimitRunRequest(const _manage_client_limit_run_request_acwr *request);
  bool ManageClientForceExitRequest();
  bool CashDBInfoRecvResult(int n, const _cashdb_info_recv_result_acwr *request);
  bool WorldServiceInform(unsigned int n, const _world_service_inform_acwr *request);
  bool WorldExitInform(unsigned int n);
  bool WorldMsgInform(unsigned int n, const _world_msg_inform_acwr *request);
  bool ChatLockCommand(unsigned int n, const _chat_lock_command_acwr *request);

  bool BillingCloseRequest(int n, const _billing_close_request_bizo *request);
  bool BillingRemaintimePersonal(int n, const _remaintime_personal_request_bizo *request);
  bool BillingRemaintimePCBang(int n, const _remaintime_pcbang_request_bizo *request);
  bool BillingChangeType(int n, const _change_type_request_bizo *request);
  bool BillingExpirePersonal(int n, const _expire_personal_request_bizo *request);
  bool BillingExpirePCBang(int n, const _expire_pcbang_request_bizo *request);
  bool BillingExpireIPOverflow(int n, const _expire_ipoverflow_request_bizo *request);
  bool BillingDestroyModule(int n);
  bool TaiwanBillingUserCertify(int n, char *pBuf);
  bool ChinaBillingChangePrimium(int n, char *pBuf);
  bool ZoneAliveCheckRequest(int n, const _zone_alive_check_request_bizo *request);

  bool LogInWebAgentServer(unsigned int n, const _login_web_agent_server_request_wazo *request);
  bool SendRaceBossMsgFromWebRequest(int n, const _send_race_boss_msg_from_web_request_wazo *request);
  bool LogInControllServer(unsigned int n, const _login_controll_server_request_wazo *request);
  bool CancelRaceBossSMSMsg(int n, char *pBuf);
  bool ConnectionStatusRequest(int n);
};

extern CNetworkEX g_Network;

void DeCrypt_Move(char *pStr, int nSize, unsigned __int8 byPlus, unsigned __int16 wCryptKey);

