#include "pch.h"

#include "CUnmannedTraderEnvironmentValue.h"

const char *CUnmannedTraderEnvironmentValue::Unmanned_Trader_Setting_Xml_File = "./Initialize/UnmendTrader.xml";
unsigned int CUnmannedTraderEnvironmentValue::Unmanned_Trader_Dev_Account_Start_Serial;
unsigned int CUnmannedTraderEnvironmentValue::Unmanned_Trader_Max_Schdule_Cnt;
unsigned int CUnmannedTraderEnvironmentValue::Unmanned_Trader_Check_Schedule_Delay;
unsigned int CUnmannedTraderEnvironmentValue::Unmanned_Trader_Change_Taxrate_Check_Changed_Day_Delay;
unsigned int CUnmannedTraderEnvironmentValue::UNMANNEDTRADETRADER_LAZYCLEANER_LOOP_DELAY;
unsigned int CUnmannedTraderEnvironmentValue::UNMANNEDTRADETRADER_LAZYCLEANER_UPDATE_MAX_RETRY_CNT;
unsigned int CUnmannedTraderEnvironmentValue::Unmanned_Trader_Max_Row_Count_Search;
unsigned int CUnmannedTraderEnvironmentValue::Unmanned_Trader_Nomal_Max_Regist_Item_Cnt;
unsigned __int8 CUnmannedTraderEnvironmentValue::Unmanned_Trader_Default_Sell_Turm;
const char *CUnmannedTraderEnvironmentValue::Unmanned_Trader_Default_Sort_Type_Name = "serial asc";
const char *CUnmannedTraderEnvironmentValue::Unmanned_Trader_Default_Sort_Query = "si.serial asc";
unsigned int CUnmannedTraderEnvironmentValue::Unmanned_Trader_Min_Limit_Empty_Record_Cnt;
unsigned int CUnmannedTraderEnvironmentValue::Unmanned_Trader_Default_Empty_Record_Cnt;
unsigned int CUnmannedTraderEnvironmentValue::UNMANNEDTRADETRADEINFO_LOOP_DELAY;
const char *CUnmannedTraderEnvironmentValue::UNMANNEDTRADETRADEINFO_SAVE_INI_SECTION_NAME = "Unmannedtradetradeinfo";
const char *CUnmannedTraderEnvironmentValue::UNMANNEDTRADETRADEINFO_SAVE_INI_FILE_NAME = "..\\SystemSave\\ServerState.ini";
