#include "pch.h"

#include "PCBANG_PRIMIUM_FAVOR.h"

float PCBANG_PRIMIUM_FAVOR::MINING_SPEED = 0.0f;
float PCBANG_PRIMIUM_FAVOR::PLAYER_EXP = 0.0f;
float PCBANG_PRIMIUM_FAVOR::ANIMUS_EXP = 0.0f;
float PCBANG_PRIMIUM_FAVOR::BASE_MASTERY = 0.0f;
float PCBANG_PRIMIUM_FAVOR::SKILL_FORCE_MASTERY = 0.0f;
float PCBANG_PRIMIUM_FAVOR::ITEM_DROP = 0.0f;
float PCBANG_PRIMIUM_FAVOR::PVP_RATE = 0.0f;
float PCBANG_PRIMIUM_FAVOR::PLAYER_LOST_EXP = 0.0f;
