-- RF_User MariaDB schema rebuilt from the Thai MSSQL references.
-- SQL-side auth procedures were intentionally not ported because the current RF_User auth
-- model depends on application-generated id_hmac / id_enc / password_hash values.
CREATE DATABASE `RF_User`;
USE `RF_User`;

CREATE TABLE `tbl_block_ip` (
	`nSerial` INT AUTO_INCREMENT NOT NULL,
	`addr0` TINYINT NOT NULL,
	`addr1` TINYINT NOT NULL,
	`addr2` TINYINT NOT NULL,
	`addr3` TINYINT NOT NULL DEFAULT 0,
	`addr4` TINYINT NOT NULL DEFAULT 255,
	`addr2range` TINYINT NOT NULL DEFAULT 255,
	PRIMARY KEY (`nSerial`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_bugtime_connect_in_pcbang` (
	`nworldcode` INT NOT NULL,
	`navatorserial` INT NULL,
	`account` CHAR(17) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_bugtime_connectpcbang` (
	`f1` TINYINT NOT NULL,
	`f2` TINYINT NOT NULL,
	`f3` TINYINT NOT NULL,
	`f4` TINYINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_connect_in_bugtime` (
	`ip` VARCHAR(16) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_connect_pcbang` (
	`ip` VARCHAR(16) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_connectpcbang_charserial` (
	`nWorldCode` TINYINT NOT NULL,
	`nAvatorSerial` INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_CristalBattle_Log` (
	`ID` INT AUTO_INCREMENT NOT NULL,
	`DID` INT NOT NULL,
	`SID` INT NOT NULL,
	`Nth` TINYINT NOT NULL,
	`MasterRace` TINYINT NOT NULL,
	`MasterName` VARCHAR(17) NOT NULL,
	`MasterClass` CHAR(4) NOT NULL,
	`B_BossName` VARCHAR(17) NOT NULL,
	`C_BossName` VARCHAR(17) NOT NULL,
	`A_BossName` VARCHAR(17) NOT NULL,
	`MasterSubBossName1` VARCHAR(17) NOT NULL,
	`MasterSubBossName2` VARCHAR(17) NOT NULL,
	`MasterSubBossName3` VARCHAR(17) NOT NULL,
	`MasterSubBossName4` VARCHAR(17) NOT NULL,
	`MasterSubBossName5` VARCHAR(17) NOT NULL,
	`StartTime` DATETIME NOT NULL,
	`GetTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`ChaosHour` TINYINT NOT NULL,
	`ChaosMin` TINYINT NOT NULL,
	`ElapseHour` TINYINT NOT NULL DEFAULT 0,
	`ElapseMin` TINYINT NOT NULL DEFAULT 0,
	`ElapseSec` TINYINT NOT NULL DEFAULT 0,
	`KeeperHitter` VARCHAR(17) NOT NULL DEFAULT ('*'),
	`ByAnimus` TINYINT NOT NULL DEFAULT 255,
	`DestroyRace` TINYINT NULL DEFAULT 255,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
ALTER TABLE `tbl_CristalBattle_Log` AUTO_INCREMENT = 220;

CREATE TABLE `tbl_exp_connectip` (
	`F1` TINYINT NOT NULL,
	`F2` TINYINT NOT NULL,
	`F3` TINYINT NOT NULL,
	`F4` TINYINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_GMActLog` (
	`ID` INT AUTO_INCREMENT NOT NULL,
	`Account` VARCHAR(17) NOT NULL,
	`TID` INT NOT NULL,
	`PID` INT NOT NULL DEFAULT 0,
	`ActDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_GMActParam` (
	`ID` INT AUTO_INCREMENT NOT NULL,
	`Param1` BLOB NULL,
	`Param2` BLOB NULL,
	`Param3` BLOB NULL,
	`Param4` BLOB NULL,
	`Param5` BLOB NULL,
	`Param6` BLOB NULL,
	`Param7` BLOB NULL,
	`Param8` BLOB NULL,
	`Param9` BLOB NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_GMActType` (
	`ID` INT NOT NULL,
	`bLog` BIT NOT NULL,
	`TypeName` VARCHAR(50) NOT NULL,
	`TypeNameKor` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_GMjobLog` (
	`nSerial` INT AUTO_INCREMENT NOT NULL,
	`szGMID` VARCHAR(18) NOT NULL,
	`nKind` TINYINT NOT NULL DEFAULT 0,
	`szAvatorName` VARCHAR(18) NULL,
	`nAvatorSerial` INT NULL,
	`nAccountSerial` INT NULL,
	`szDetail` VARCHAR(50) NOT NULL,
	`dtDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`nSerial`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_HolyQuest_Log` (
	`serial` INT AUTO_INCREMENT NOT NULL,
	`ServerName` VARCHAR(32) NOT NULL,
	`race` TINYINT NOT NULL,
	`CharName` VARCHAR(17) NOT NULL,
	`LogDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`dstRace` TINYINT NOT NULL,
	PRIMARY KEY (`serial`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_HostAccount` (
	`Account` VARCHAR(17) NOT NULL,
	`Password` VARCHAR(17) NOT NULL DEFAULT ('*'),
	`Serial` INT AUTO_INCREMENT NOT NULL,
	`Grade` TINYINT NOT NULL DEFAULT 0,
	`Depart` VARCHAR(24) NULL,
	`RealName` VARCHAR(12) NULL,
	`Grade1` TINYINT NOT NULL DEFAULT 0,
	PRIMARY KEY (`Account`),
	UNIQUE KEY `UX_tbl_HostAccount_Serial` (`Serial`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_iplist_pcbang` (
	`IP1` TINYINT NOT NULL,
	`IP2` TINYINT NOT NULL,
	`IP3` TINYINT NOT NULL,
	`IP4` TINYINT NOT NULL,
	`lastip` TINYINT NOT NULL,
	PRIMARY KEY (`IP1`, `IP2`, `IP3`, `IP4`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_protocolaccesslog` (
	`Idx` INT AUTO_INCREMENT NOT NULL,
	`ProtocolMsgID` INT NOT NULL DEFAULT 0,
	`ProtocolID` INT NOT NULL DEFAULT 0,
	`GMSerial` INT NOT NULL DEFAULT 0,
	`AccessDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`ProtocolFld0` BINARY(128) NULL,
	`ProtocolFld1` BINARY(128) NULL,
	`ProtocolFld2` BINARY(128) NULL,
	`ProtocolFld3` BINARY(128) NULL,
	`ProtocolFld4` BINARY(128) NULL,
	`ProtocolFld5` BINARY(128) NULL,
	`ProtocolFld6` BINARY(128) NULL,
	`ProtocolFld7` BINARY(128) NULL,
	`ProtocolFld8` BINARY(128) NULL,
	`ProtocolFld9` BINARY(128) NULL,
	PRIMARY KEY (`Idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_protocolauthinfo` (
	`Idx` INT AUTO_INCREMENT NOT NULL,
	`dck` BIT NOT NULL DEFAULT 0,
	`P_MsgID` INT NOT NULL DEFAULT 0,
	`P_ID` INT NOT NULL DEFAULT 0,
	`P_AuthType` TINYINT NOT NULL DEFAULT 0,
	`GMID` VARCHAR(17) NOT NULL DEFAULT ('*'),
	`GMSerial` INT NOT NULL DEFAULT 0,
	PRIMARY KEY (`Idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_protocolinfo` (
	`Idx` INT AUTO_INCREMENT NOT NULL,
	`dck` BIT NOT NULL DEFAULT 0,
	`ProtocolMsgID` INT NOT NULL DEFAULT 0,
	`ProtocolID` INT NOT NULL DEFAULT 0,
	`ProtocolName` VARCHAR(64) NOT NULL DEFAULT ('*'),
	`ProtocolExplain` VARCHAR(256) NOT NULL DEFAULT ('*'),
	`ProtocolFldCnt` TINYINT NOT NULL DEFAULT 0,
	`UpdateDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`Idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_rfaccount` (
	`id_hmac` BINARY(32) NOT NULL,
	`id_enc` VARBINARY(128) NOT NULL,
	`password_hash` VARCHAR(255) NOT NULL,
	`accounttype` TINYINT NOT NULL DEFAULT 0,
	`birthdate` DATETIME NULL,
	PRIMARY KEY (`id_hmac`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_ServerUser_Log` (
	`serial` INT AUTO_INCREMENT NOT NULL,
	`dtDate` DATETIME NOT NULL,
	`nAverageUser` INT NOT NULL DEFAULT 0,
	`nMaxUser` INT NOT NULL DEFAULT 0,
	`ServerName` VARCHAR(32) NOT NULL,
	`nBellaUser` INT NOT NULL DEFAULT 0,
	`nCoraUser` INT NOT NULL DEFAULT 0,
	`nAccUser` INT NOT NULL DEFAULT 0,
	PRIMARY KEY (`serial`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_StaffAccount` (
	`Serial` INT AUTO_INCREMENT NOT NULL,
	`ID_hmac` BINARY(32) NOT NULL,
	`ID_enc` VARBINARY(128) NOT NULL,
	`PW_hash` VARCHAR(255) NOT NULL,
	`Grade` TINYINT NOT NULL DEFAULT ((1)),
	`Depart` VARCHAR(32) NOT NULL,
	`RealName` VARCHAR(12) NOT NULL,
	`LastConnIP` CHAR(16) NOT NULL DEFAULT '0',
	`CreateDT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`LastLoginDT` DATETIME NOT NULL DEFAULT 0,
	`LastLogoffDT` DATETIME NOT NULL DEFAULT 0,
	`TotalLogMin` INT NOT NULL DEFAULT 0,
	`SubGrade` TINYINT NOT NULL DEFAULT 0,
	`ExpireDT` DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP + INTERVAL 1 MONTH),
	`ComClass` VARCHAR(12) NOT NULL DEFAULT '??',
	`BirthDay` CHAR(10) NOT NULL DEFAULT '',
	PRIMARY KEY (`Serial`),
	UNIQUE KEY `IX_tbl_StaffAccount` (`ID_hmac`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
ALTER TABLE `tbl_StaffAccount` AUTO_INCREMENT = 2000000000;

CREATE TABLE `tbl_UserAccount` (
	`serial` INT NOT NULL AUTO_INCREMENT,
	`id_hmac` BINARY(32) NOT NULL,
	`id_enc` VARBINARY(128) NOT NULL,
	`createtime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`createip` CHAR(16) NOT NULL DEFAULT '0',
	`lastlogintime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lastlogofftime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`totallogmin` INT NOT NULL DEFAULT 0,
	`lastconnectip` CHAR(16) NOT NULL DEFAULT '0',
	`pushclosetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`pusherip` CHAR(16) NOT NULL DEFAULT '0',
	`JoinCode` INT NOT NULL DEFAULT 0,
	`LoginFailureCnt` TINYINT NOT NULL DEFAULT 0,
	`fire_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`fire_warning` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`uilock` TINYINT NOT NULL DEFAULT 0,
	`uilock_pw` VARCHAR(255) NOT NULL DEFAULT '',
	`uilock_failcnt` TINYINT NOT NULL DEFAULT 0,
	`uilock_update` DATETIME NOT NULL DEFAULT 0,
	`uilock_hintindex` TINYINT NOT NULL DEFAULT 0,
	`uilock_hintanswer` VARCHAR(255) NOT NULL DEFAULT '',
	`uilock_find_pass_failcnt` TINYINT NOT NULL DEFAULT 0,
	PRIMARY KEY (`id_hmac`),
	UNIQUE KEY `IX_tbl_rfuser` (`serial`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_UserBan` (
	`nAccountSerial` INT NOT NULL,
	`dtStartDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`nPeriod` INT NOT NULL,
	`nKind` TINYINT NOT NULL DEFAULT 0,
	`szReason` VARCHAR(32) NULL,
	`GMReason` VARCHAR(32) NOT NULL DEFAULT ('*'),
	`GMWriter` VARCHAR(32) NOT NULL DEFAULT ('*'),
	`reasontype` TINYINT NOT NULL DEFAULT 0,
	PRIMARY KEY (`nAccountSerial`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_UserBan_Log` (
	`nSerial` INT AUTO_INCREMENT NOT NULL,
	`nAccountSerial` INT NOT NULL,
	`dtStartdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`nPeriod` INT NOT NULL,
	`nKind` TINYINT NOT NULL DEFAULT 0,
	`szReason` VARCHAR(32) NULL,
	`GMReason` VARCHAR(32) NOT NULL DEFAULT ('*'),
	`GMWriter` VARCHAR(32) NOT NULL DEFAULT ('*'),
	PRIMARY KEY (`nSerial`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_UserCount_Log` (
	`serial` INT AUTO_INCREMENT NOT NULL,
	`dtDate` DATETIME NOT NULL,
	`nAverageUser` INT NOT NULL DEFAULT 0,
	`nMaxUser` INT NOT NULL DEFAULT 0,
	`nMaxUserTestServer` INT NOT NULL DEFAULT 0,
	PRIMARY KEY (`serial`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_usercurrentstate` (
	`serial` INT NOT NULL,
	`state` TINYINT NOT NULL DEFAULT 0,
	PRIMARY KEY (`serial`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_UserPush_Log` (
	`nAccountSerial` INT NOT NULL DEFAULT 0,
	`dtDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`PushIP` VARCHAR(16) NOT NULL DEFAULT '0',
	`CloseIP` VARCHAR(16) NOT NULL DEFAULT '0',
	PRIMARY KEY (`nAccountSerial`, `dtDate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_WorldHistory_Log` (
	`serverName` CHAR(12) NOT NULL,
	`race` CHAR(12) NOT NULL,
	`avatorNum` INT NOT NULL DEFAULT 0,
	`dalant` BIGINT NOT NULL DEFAULT 0,
	`gold` BIGINT NOT NULL DEFAULT 0,
	`lv` INT NOT NULL,
	`logDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`idx` INT AUTO_INCREMENT NOT NULL,
	PRIMARY KEY (`idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_WorldServer_List` (
	`Serial` INT NOT NULL,
	`Name` VARCHAR(32) NOT NULL,
	`State` INT NOT NULL,
	`LastUpdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`msrepl_tran_version` CHAR(36) NOT NULL DEFAULT (newid()),
	PRIMARY KEY (`Serial`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_UserLogout_Log` (
	`nAccountSerial` INT NOT NULL,
	`nCounter` INT NOT NULL,
	`dtLoginDate` DATETIME NOT NULL,
	`dtLogoutDate` DATETIME NOT NULL,
	`ip` CHAR(16) NOT NULL,
	PRIMARY KEY (`nAccountSerial`, `nCounter`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_fg_detected_account` (
	`account` VARCHAR(16) NOT NULL,
	`detect_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`account`, `detect_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `tbl_fg_detected_ip` (
	`ip` INT NOT NULL,
	`detect_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`ip`, `detect_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
