-- RF_User SQLite schema rebuilt from the Thai MSSQL references.
-- SQLite has no stored procedures, and secure RF_User auth is handled by the application layer.

CREATE TABLE `tbl_block_ip` (
	`nSerial` INTEGER PRIMARY KEY AUTOINCREMENT,
	`addr0` INTEGER NOT NULL,
	`addr1` INTEGER NOT NULL,
	`addr2` INTEGER NOT NULL,
	`addr3` INTEGER NOT NULL DEFAULT 0,
	`addr4` INTEGER NOT NULL DEFAULT 255,
	`addr2range` INTEGER NOT NULL DEFAULT 255
);

CREATE TABLE `tbl_bugtime_connect_in_pcbang` (
	`nworldcode` INTEGER NOT NULL,
	`navatorserial` INTEGER NULL,
	`account` TEXT NULL
);

CREATE TABLE `tbl_bugtime_connectpcbang` (
	`f1` INTEGER NOT NULL,
	`f2` INTEGER NOT NULL,
	`f3` INTEGER NOT NULL,
	`f4` INTEGER NOT NULL
);

CREATE TABLE `tbl_connect_in_bugtime` (
	`ip` TEXT NOT NULL
);

CREATE TABLE `tbl_connect_pcbang` (
	`ip` TEXT NOT NULL
);

CREATE TABLE `tbl_connectpcbang_charserial` (
	`nWorldCode` INTEGER NOT NULL,
	`nAvatorSerial` INTEGER NOT NULL
);

CREATE TABLE `tbl_CristalBattle_Log` (
	`ID` INTEGER PRIMARY KEY AUTOINCREMENT,
	`DID` INTEGER NOT NULL,
	`SID` INTEGER NOT NULL,
	`Nth` INTEGER NOT NULL,
	`MasterRace` INTEGER NOT NULL,
	`MasterName` TEXT NOT NULL,
	`MasterClass` TEXT NOT NULL,
	`B_BossName` TEXT NOT NULL,
	`C_BossName` TEXT NOT NULL,
	`A_BossName` TEXT NOT NULL,
	`MasterSubBossName1` TEXT NOT NULL,
	`MasterSubBossName2` TEXT NOT NULL,
	`MasterSubBossName3` TEXT NOT NULL,
	`MasterSubBossName4` TEXT NOT NULL,
	`MasterSubBossName5` TEXT NOT NULL,
	`StartTime` TEXT NOT NULL,
	`GetTime` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`ChaosHour` INTEGER NOT NULL,
	`ChaosMin` INTEGER NOT NULL,
	`ElapseHour` INTEGER NOT NULL DEFAULT 0,
	`ElapseMin` INTEGER NOT NULL DEFAULT 0,
	`ElapseSec` INTEGER NOT NULL DEFAULT 0,
	`KeeperHitter` TEXT NOT NULL DEFAULT ('*'),
	`ByAnimus` INTEGER NOT NULL DEFAULT 255,
	`DestroyRace` INTEGER NULL DEFAULT 255
);
INSERT INTO sqlite_sequence(name, seq) VALUES('tbl_CristalBattle_Log', 219);

CREATE TABLE `tbl_exp_connectip` (
	`F1` INTEGER NOT NULL,
	`F2` INTEGER NOT NULL,
	`F3` INTEGER NOT NULL,
	`F4` INTEGER NOT NULL
);

CREATE TABLE `tbl_GMActLog` (
	`ID` INTEGER PRIMARY KEY AUTOINCREMENT,
	`Account` TEXT NOT NULL,
	`TID` INTEGER NOT NULL,
	`PID` INTEGER NOT NULL DEFAULT 0,
	`ActDate` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `tbl_GMActParam` (
	`ID` INTEGER PRIMARY KEY AUTOINCREMENT,
	`Param1` BLOB NULL,
	`Param2` BLOB NULL,
	`Param3` BLOB NULL,
	`Param4` BLOB NULL,
	`Param5` BLOB NULL,
	`Param6` BLOB NULL,
	`Param7` BLOB NULL,
	`Param8` BLOB NULL,
	`Param9` BLOB NULL
);

CREATE TABLE `tbl_GMActType` (
	`ID` INTEGER NOT NULL,
	`bLog` INTEGER NOT NULL,
	`TypeName` TEXT NOT NULL,
	`TypeNameKor` TEXT NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `tbl_GMjobLog` (
	`nSerial` INTEGER PRIMARY KEY AUTOINCREMENT,
	`szGMID` TEXT NOT NULL,
	`nKind` INTEGER NOT NULL DEFAULT 0,
	`szAvatorName` TEXT NULL,
	`nAvatorSerial` INTEGER NULL,
	`nAccountSerial` INTEGER NULL,
	`szDetail` TEXT NOT NULL,
	`dtDate` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `tbl_HolyQuest_Log` (
	`serial` INTEGER PRIMARY KEY AUTOINCREMENT,
	`ServerName` TEXT NOT NULL,
	`race` INTEGER NOT NULL,
	`CharName` TEXT NOT NULL,
	`LogDate` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`dstRace` INTEGER NOT NULL
);

CREATE TABLE `tbl_HostAccount` (
	`Account` TEXT NOT NULL,
	`Password` TEXT NOT NULL DEFAULT ('*'),
	`Serial` INTEGER NOT NULL,
	`Grade` INTEGER NOT NULL DEFAULT 0,
	`Depart` TEXT NULL,
	`RealName` TEXT NULL,
	`Grade1` INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (`Account`)
);

CREATE TABLE `tbl_iplist_pcbang` (
	`IP1` INTEGER NOT NULL,
	`IP2` INTEGER NOT NULL,
	`IP3` INTEGER NOT NULL,
	`IP4` INTEGER NOT NULL,
	`lastip` INTEGER NOT NULL,
	PRIMARY KEY (`IP1`, `IP2`, `IP3`, `IP4`)
);

CREATE TABLE `tbl_protocolaccesslog` (
	`Idx` INTEGER PRIMARY KEY AUTOINCREMENT,
	`ProtocolMsgID` INTEGER NOT NULL DEFAULT 0,
	`ProtocolID` INTEGER NOT NULL DEFAULT 0,
	`GMSerial` INTEGER NOT NULL DEFAULT 0,
	`AccessDate` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`ProtocolFld0` BLOB NULL,
	`ProtocolFld1` BLOB NULL,
	`ProtocolFld2` BLOB NULL,
	`ProtocolFld3` BLOB NULL,
	`ProtocolFld4` BLOB NULL,
	`ProtocolFld5` BLOB NULL,
	`ProtocolFld6` BLOB NULL,
	`ProtocolFld7` BLOB NULL,
	`ProtocolFld8` BLOB NULL,
	`ProtocolFld9` BLOB NULL
);

CREATE TABLE `tbl_protocolauthinfo` (
	`Idx` INTEGER PRIMARY KEY AUTOINCREMENT,
	`dck` INTEGER NOT NULL DEFAULT 0,
	`P_MsgID` INTEGER NOT NULL DEFAULT 0,
	`P_ID` INTEGER NOT NULL DEFAULT 0,
	`P_AuthType` INTEGER NOT NULL DEFAULT 0,
	`GMID` TEXT NOT NULL DEFAULT ('*'),
	`GMSerial` INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE `tbl_protocolinfo` (
	`Idx` INTEGER PRIMARY KEY AUTOINCREMENT,
	`dck` INTEGER NOT NULL DEFAULT 0,
	`ProtocolMsgID` INTEGER NOT NULL DEFAULT 0,
	`ProtocolID` INTEGER NOT NULL DEFAULT 0,
	`ProtocolName` TEXT NOT NULL DEFAULT ('*'),
	`ProtocolExplain` TEXT NOT NULL DEFAULT ('*'),
	`ProtocolFldCnt` INTEGER NOT NULL DEFAULT 0,
	`UpdateDate` TEXT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `tbl_rfaccount` (
	`id_hmac` BLOB NOT NULL,
	`id_enc` BLOB NOT NULL,
	`password_hash` TEXT NOT NULL,
	`accounttype` INTEGER NOT NULL DEFAULT 0,
	`birthdate` TEXT NULL,
	PRIMARY KEY (`id_hmac`)
);

CREATE TABLE `tbl_ServerUser_Log` (
	`serial` INTEGER PRIMARY KEY AUTOINCREMENT,
	`dtDate` TEXT NOT NULL,
	`nAverageUser` INTEGER NOT NULL DEFAULT 0,
	`nMaxUser` INTEGER NOT NULL DEFAULT 0,
	`ServerName` TEXT NOT NULL,
	`nBellaUser` INTEGER NOT NULL DEFAULT 0,
	`nCoraUser` INTEGER NOT NULL DEFAULT 0,
	`nAccUser` INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE `tbl_StaffAccount` (
	`Serial` INTEGER PRIMARY KEY AUTOINCREMENT,
	`ID_hmac` BLOB NOT NULL,
	`ID_enc` BLOB NOT NULL,
	`PW_hash` TEXT NOT NULL,
	`Grade` INTEGER NOT NULL DEFAULT ((1)),
	`Depart` TEXT NOT NULL,
	`RealName` TEXT NOT NULL,
	`LastConnIP` TEXT NOT NULL DEFAULT '0',
	`CreateDT` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`LastLoginDT` TEXT NOT NULL DEFAULT 0,
	`LastLogoffDT` TEXT NOT NULL DEFAULT 0,
	`TotalLogMin` INTEGER NOT NULL DEFAULT 0,
	`SubGrade` INTEGER NOT NULL DEFAULT 0,
	`ExpireDT` TEXT NOT NULL DEFAULT (datetime('now', '+1 month')),
	`ComClass` TEXT NOT NULL DEFAULT '??',
	`BirthDay` TEXT NOT NULL DEFAULT '',
	UNIQUE (`ID_hmac`)
);
INSERT INTO sqlite_sequence(name, seq) VALUES('tbl_StaffAccount', 1999999999);

CREATE TABLE `tbl_UserAccount` (
	`serial` INTEGER PRIMARY KEY AUTOINCREMENT,
	`id_hmac` BLOB NOT NULL,
	`id_enc` BLOB NOT NULL,
	`createtime` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`createip` TEXT NOT NULL DEFAULT '0',
	`lastlogintime` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lastlogofftime` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`totallogmin` INTEGER NOT NULL DEFAULT 0,
	`lastconnectip` TEXT NOT NULL DEFAULT '0',
	`pushclosetime` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`pusherip` TEXT NOT NULL DEFAULT '0',
	`JoinCode` INTEGER NOT NULL DEFAULT 0,
	`LoginFailureCnt` INTEGER NOT NULL DEFAULT 0,
	`fire_on` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`fire_warning` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`uilock` INTEGER NOT NULL DEFAULT 0,
	`uilock_pw` TEXT NOT NULL DEFAULT '',
	`uilock_failcnt` INTEGER NOT NULL DEFAULT 0,
	`uilock_update` TEXT NOT NULL DEFAULT 0,
	`uilock_hintindex` INTEGER NOT NULL DEFAULT 0,
	`uilock_hintanswer` TEXT NOT NULL DEFAULT '',
	`uilock_find_pass_failcnt` INTEGER NOT NULL DEFAULT 0,
	UNIQUE (`id_hmac`)
);

CREATE TABLE `tbl_UserBan` (
	`nAccountSerial` INTEGER NOT NULL,
	`dtStartDate` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`nPeriod` INTEGER NOT NULL,
	`nKind` INTEGER NOT NULL DEFAULT 0,
	`szReason` TEXT NULL,
	`GMReason` TEXT NOT NULL DEFAULT ('*'),
	`GMWriter` TEXT NOT NULL DEFAULT ('*'),
	`reasontype` INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (`nAccountSerial`)
);

CREATE TABLE `tbl_UserBan_Log` (
	`nSerial` INTEGER PRIMARY KEY AUTOINCREMENT,
	`nAccountSerial` INTEGER NOT NULL,
	`dtStartdate` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`nPeriod` INTEGER NOT NULL,
	`nKind` INTEGER NOT NULL DEFAULT 0,
	`szReason` TEXT NULL,
	`GMReason` TEXT NOT NULL DEFAULT ('*'),
	`GMWriter` TEXT NOT NULL DEFAULT ('*')
);

CREATE TABLE `tbl_UserCount_Log` (
	`serial` INTEGER PRIMARY KEY AUTOINCREMENT,
	`dtDate` TEXT NOT NULL,
	`nAverageUser` INTEGER NOT NULL DEFAULT 0,
	`nMaxUser` INTEGER NOT NULL DEFAULT 0,
	`nMaxUserTestServer` INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE `tbl_usercurrentstate` (
	`serial` INTEGER NOT NULL,
	`state` INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (`serial`)
);

CREATE TABLE `tbl_UserPush_Log` (
	`nAccountSerial` INTEGER NOT NULL DEFAULT 0,
	`dtDate` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`PushIP` TEXT NOT NULL DEFAULT '0',
	`CloseIP` TEXT NOT NULL DEFAULT '0',
	PRIMARY KEY (`nAccountSerial`, `dtDate`)
);

CREATE TABLE `tbl_WorldHistory_Log` (
	`serverName` TEXT NOT NULL,
	`race` TEXT NOT NULL,
	`avatorNum` INTEGER NOT NULL DEFAULT 0,
	`dalant` INTEGER NOT NULL DEFAULT 0,
	`gold` INTEGER NOT NULL DEFAULT 0,
	`lv` INTEGER NOT NULL,
	`logDate` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`idx` INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE `tbl_WorldServer_List` (
	`Serial` INTEGER NOT NULL,
	`Name` TEXT NOT NULL,
	`State` INTEGER NOT NULL,
	`LastUpdate` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`msrepl_tran_version` TEXT NOT NULL DEFAULT (newid()),
	PRIMARY KEY (`Serial`)
);

CREATE TABLE `tbl_UserLogout_Log` (
	`nAccountSerial` INTEGER NOT NULL,
	`nCounter` INTEGER NOT NULL,
	`dtLoginDate` TEXT NOT NULL,
	`dtLogoutDate` TEXT NOT NULL,
	`ip` TEXT NOT NULL,
	PRIMARY KEY (`nAccountSerial`, `nCounter`)
);

CREATE TABLE `tbl_fg_detected_account` (
	`account` TEXT NOT NULL,
	`detect_time` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`account`, `detect_time`)
);

CREATE TABLE `tbl_fg_detected_ip` (
	`ip` INTEGER NOT NULL,
	`detect_time` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`ip`, `detect_time`)
);
