[Config]
; item combination delay in milliseconds
DELAY_COMBINE = 3000
; prevent mouse movement
DISABLE_MOVE_BY_MOUSE = false
; add socket/upgrader/combiner/ore to system menu
SYSTEM_MENU_EX = true

[Window]
; premium users get +1 extra window
EXTRA_WINDOW_PREM = false
; max windows without premium
FREE_WINDOW = 1
; max windows total
MAX_WINDOW = 2

[BossSchedule]
; boss schedule button on radar
Enable = true
