[Config]
MINIMUM_JOIN_LEVEL = 30
CREATE_GUILD_MONEY = 24000000
CREATE_EMBLEM_MONEY = 3000000

[GvG]
; set 0 to disable guild vs guild registration
MAX_REGIST = 1
MIN_SUGGESTING_GRADE = 3

[HonorGuild]
; true = original system (race leader assigns), false = fixed system
FIX = false

[GuildRoom]
; set false to disable guild rooms
Enable = true
