;; Player Configuration
;; some config here can't auto reload

[Player]
; max level on tbl_general, default is 50
MAX_LEVEL = 50
; limit player exp at max level (default is 66, if value > 66 : pvp limitpoint auto set)
LIMIT_EXP_LEVEL = 66
; maximum players dalant
MAX_DALANT = 2000000000
; maximum players gold
MAX_GOLD = 500000
; minimum player can chat type All
MIN_CHAT_ALL_LEVEL = 30
; player cannot transaction trade or loot after this time (time is second, 60 = 1 minutes)
DELAY_TRANSACTION = 60
; limit to configure the speed, do not touch this
MOVE_SPEED_STEP = 1.150
; if you encounter problems, increase the value tolerance (e.g., 0.5, 0.75, 1.0, or higher)
MOVE_SPEED_TOLERANCE = 0.2
; max speed hack violations before auto-kick
SPEED_HACK_MAX_COUNT = 10
; auto kick on speed hack
SPEED_HACK_AUTO_KICK = true

[Animus]
; the default maximum level record on animus script is 66, so this level is set to 65
MAX_LEVEL_RECORD = 65
; distance level rule between player and animus
DISTANCE_LEVEL = 1
; recommended value is 30
MIN_MASTER_LEVEL = 50

[Unit]
; set true if MAU can get exp from monster
GET_EXP = false
; delay after MAU delivery in milliseconds
DELAY_DELIVERY = 2500

[InvisHack]
; auto kick on invis hack detection
AutoKick = false
; when 0 detection is disabled, set 5 is recommended
MaxTrigger = 0

[PvpShare]
; shared pvp point on party
Enable = true
; 0 = evenly distributed, 1 = calculated (killer gets more)
SharedType = 1
