[Config]
; return tower after player disconnects
ReturnAfterDisconnect = true

[License]
; require license item to build tower
Enable = false
Num = 2

; GuardTowerLv: minimum level to build
; WorkOnMap: "all" or comma-separated map indices
; LicenseItem: booty item code used as license

GuardTowerLv0 = 35
WorkOnMap0 = all
LicenseItem0 = iyyyy23

GuardTowerLv1 = 40
WorkOnMap1 = 10,11,12,13
LicenseItem1 = iyyyy23
